language: perl
perl:
   - '5.10'
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
   - cpanm Dist::Zilla
   - cpanm https://cpan.metacpan.org/authors/id/K/KE/KEEDI/Dist-Zilla-Plugin-GitFlow-0.010.tar.gz
   - cpanm Pod::Elemental::Transformer::List
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
   - "dzil authordeps | xargs cpanm"
install:
   - "dzil listdeps --author | xargs cpanm"
script:
   - dzil smoke --release --author
