language: perl
perl:
    - '5.10'
    - '5.12'
    - '5.14'
    - '5.16'
    - '5.18'
    - '5.20'
env: PERL_CPANM_OPT="--quiet --notest --force --skip-satisfied" RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
before_install:
    - git clone git://github.com/haarg/perl-travis-helper
    - source perl-travis-helper/init
    - build-perl
    - perl -V
    - cpanm Dist::Zilla
    - cpanm Devel::Cover::Report::Coveralls
    - cpanm Dist::Zilla::App::Command::cover
    - cpanm https://cpan.metacpan.org/authors/id/K/KE/KEEDI/Dist-Zilla-Plugin-GitFlow-0.010.tar.gz
    - cpanm Pod::Elemental::Transformer::List
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - "dzil authordeps | grep -vP ‘[^\w:]‘ | xargs -n 5 -P 10 cpanm"
    - "dzil listdeps --author | cpanm"
install:
    - "dzil listdeps | grep -vP ‘[^\w:]‘ | cpanm"
script:
    - dzil smoke --release --author
after_success:
    - dzil cover -outputdir cover_db -report coveralls
